---
# iptables is not installed in RHEL7 by default and hence need to install it and disable firewalld
#
# Note: This task was originally written for RHEL7.  It was found to be compatible with CentOS7 'as is'
#       More recently, the 'when' clause has been updated to allow this task to run on 'version >= 7'


- name: install iptables services (RHEL/CentOS compatible with >= 7)
  become: true
  package: name=iptables-services state=present
  when: ansible_os_family == "RedHat" and (ansible_distribution_version | int) >= 7

- name: stop firewalld
  become: true
  command: "systemctl stop firewalld"
  when: ansible_os_family == "RedHat" and (ansible_distribution_version | int) >= 7

- name: mask firewalld
  become: true
  command: "systemctl mask firewalld"
  when: ansible_os_family == "RedHat" and (ansible_distribution_version | int) >= 7

- name: enable iptables
  become: true
  command: "systemctl enable iptables"
  when: ansible_os_family == "RedHat" and (ansible_distribution_version | int) >= 7

- name: start iptables
  become: true
  command: "systemctl start iptables"
  when: ansible_os_family == "RedHat" and (ansible_distribution_version | int) >= 7
