---
- name: Add EPEL yum repository for RedHat/CentOS 8
  become: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 8  
  yum_repository:
   name: epel
   description: EPEL YUM repo
   baseurl: https://download.fedoraproject.org/pub/epel/8/Everything/x86_64/
   gpgcheck: no

- name: Install required packages for RedHat/CentOS 8
  become: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == 8  
  package: name={{ item }} state=present
  with_items:
   - "@Virtualization Host"

